### ISSUE TITLE
PushToUnmappedRepo failing because of null

### ISSUE THREAD

**Issue by ddgenome** [atomist/lifecycle-automation#123]
Here is the log:

```
2018-01-22T22:18:59.274Z [w:22:c3d53c8a-48e6-4019-815d-a17ef5108e40:atomist:PushToUnmappedRepo:010] [error] Failed invocation of event subscription 'PushToUnmappedRepo': {"name":"TypeError","message":"Cannot read property 'includes' of null","stack":"TypeError: Cannot read property 'includes' of null\n    at channels.filter.c (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:150:54)\n    at Array.filter (<anonymous>)\n    at fuzzyRepoChannelMatch (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:150:35)\n    at mapRepoMessage (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:188:32)\n    at Promise.all.enabledChatIds.map.chatId (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:68:39)\n    at Array.map (<anonymous>)\n    at sendUnMappedRepoMessage (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:66:39)\n    at Promise.all.e.data.Push.map.p (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:46:20)\n    at Array.map (<anonymous>)\n    at PushToUnmappedRepo.handle (/app/build/src/handlers/event/push/PushToUnmappedRepo.js:24:40)\n    at BuildableAutomationServer.invokeFreshEventHandlerInstance (/app/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:137:18)\n    at Object.invoke (/app/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:91:38)\n    at BuildableAutomationServer.invokeEventHandler (/app/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:107:24)\n    at Promise.all.h.map.eh (/app/node_modules/@atomist/automation-client/server/AbstractAutomationServer.js:18:49)\n    at Array.map (<anonymous>)\n    at BuildableAutomationServer.onEvent (/app/node_modules/@atomist/automation-client/server/AbstractAutomationServer.js:18:34)"}
```

First reported by @kipz

**Comment by ddgenome** [comment]
Apparently some channels do not have names.

**Comment by ddgenome** [comment]
Looks like the names of DMs, should they somehow make it into the channel list, are null.
