### ISSUE TITLE
Creating issue reports an error when creating issue from a DM

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#213]
When I create an issue in a DM with `@atomist` issue gets created but I also get an error (in staging):

Unable to run command
Unsuccessfully invoked command CreateGitHubIssue of @atomist/lifecycle-automation@0.6.3-20180509202728
Correlation ID: 99c0a6d3-5e27-4f09-99dc-1329a579e5e8

Error in logs:

```
Error: Repository is missing providerType
    at Object.userUrl (/opt/app/src/util/helpers.ts:151:15)
    at IssueNodeRenderer.render (/opt/app/src/handlers/event/issue/rendering/IssueNodeRenderers.ts:95:27)
    at lifecycle.contributors.filter.reduce.then.actions (/opt/app/src/lifecycle/Lifecycle.ts:117:46)
    at propagateAslWrapper (/opt/app/node_modules/async-listener/index.js:502:23)
    at /opt/app/node_modules/async-listener/glue.js:188:31
    at proxyWrapper (/opt/app/node_modules/async-listener/index.js:511:29)
    at proxyWrapper (/opt/app/node_modules/async-listener/index.js:511:29)
    at /opt/app/node_modules/async-listener/index.js:539:70
    at /opt/app/node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by cdupuis** [comment]
Fixed in 55557e784848f114b486843812bd75ba514b032a
