### ISSUE TITLE
Exposing kickUserFromSlackChannel

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#257]
This is ready in prod now.
```
mutation kickUserFromSlackChannel(
  $teamId: String!
  $channelId: String!
  $userId: String!
) {
  kickUserFromSlackChannel(
    chatTeamId: $teamId
    channelId: $channelId
    userId: $userId
  ) {
    id
  }
}
```
As discussed, a customer is integrating the lifecycle command handler for the corresponding inviteUserToSlackChannel mutation.

**Comment by cdupuis** [comment]
I added `kickUserFromSlackChannel` for that. 

Right now running the mutation returns the following error but the user is successfully picked. Raised issue in backend.

```
2018-11-05T17:28:58.542Z [m:53432:869cc6b7-5c57-4e83-935d-be67322ed101:atomist:KickUserFromSlackChannel:2174] [error] Failed invocation of command 'KickUserFromSlackChannel': 
Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/src/errors/ApolloError.ts:56:5)
    at Object.error (/Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/src/core/QueryManager.ts:289:13)
    at notifySubscription (/Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:224:7)
    at /Users/cdupuis/Development/atomist/lifecycle-automation/node_modules/apollo-link-http/src/httpLink.ts:165:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
