### ISSUE TITLE
CreateGitHubIssue fails for unmapped channels

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#53]
```
TypeError: Cannot read property 'find' of undefined
    at IssueToIssueLifecycle.groupChannels (/app/build/src/lifecycle/Lifecycle.js:154:40)
    at lifecycles.map.lifecycle (/app/build/src/lifecycle/Lifecycle.js:35:41)
    at Array.map (<anonymous>)
    at IssueToIssueLifecycle.handle (/app/build/src/lifecycle/Lifecycle.js:34:36)
    at helpers_1.replaceChatIdWithGitHubId.then.then.then.then.result (/app/build/src/handlers/command/github/CreateGitHubIssue.js:74:32)
    at propagateAslWrapper (/app/node_modules/async-listener/index.js:478:23)
    at /app/node_modules/async-listener/glue.js:188:31
    at proxyWrapper (/app/node_modules/async-listener/index.js:487:29)
    at /app/node_modules/async-listener/index.js:515:70
    at /app/node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by cdupuis** [comment]
This has been addressed in master.
